### PR TITLE
Avoid some deprecation messages triggered by latest stable dmd v2.097.2

### PR DESCRIPTION
**Pull request by nordlow**
Please tag afterwards.

What's the status of moving this to dlang-community, @John-Colvin?

### CODE REVIEW

**Comment by nordlow** [comment]
Can we have this merged, please?

**Comment by nordlow** [comment]
If @repeatedly shall I fork this to dlang-community, @John-Colvin @Maxhaton?

**Comment by maxhaton** [comment]
Either that or company GitHub.

**Comment by maxhaton** [comment]
I'd want spiritual permission from the author to fork into dlang-community if possible. Forking to our GitHub is different because we are just us rather than the D community.

**Comment by RazvanN7** [comment]
Are you asking if it's ok to fork this project to dlang-community? I'm not sure what the procedure is though...

If this is causing builkite errors, we can just remove it from the list of projects that are being tested.

**Comment by nordlow** [comment]
> Are you asking if it's ok to fork this project to dlang-community? I'm not sure what the procedure is though...
> 
> If this is causing builkite errors, we can just remove it from the list of projects that are being tested.

No, it is causing deprecation warnings in our company private builds.

**Comment by nordlow** [comment]
> I'd want spiritual permission from the author to fork into dlang-community if possible. Forking to our GitHub is different because we are just us rather than the D community.

Yes, I very much agree on this.

**Comment by nordlow** [comment]
Who decides to make dlang-community fork the one that dub selects from code.dlang.org.?

**Comment by nordlow** [comment]
@maxhaton, can you create a dlang-community fork for msgpack-d I can push to?

**Comment by o3o** [comment]
Any news about dlang-community fork ?
Thanks

**Comment by lempiji** [comment]
Hello.
I have been authorized by @repeatedly to do merges, etc.
I will maintain this repo for a while from now on.

As for the fixes, #123 and #124 contain the same content, so I would like to merge those and close this PR.
After the merge, I will tag v1.0.4

Please comment if any suggestions.

**Comment by nordlow** [comment]
Ok. Thanks.

**Comment by lempiji** [comment]
After comparing it with similar PR, this PR was simple and easy to understand for me.

I will merge this one as I want to release it as soon as possible. 
Thanks!

**Comment by lempiji** [comment]
Fix #123

**Pull request merged**
