### PR TITLE
Close #48: convert to/from json

### LINKED ISSUE #48: convert from/to json
is there a way to convert from/to json ?

### PR DESCRIPTION
**Pull request by Groterik**
Simple converter msgpack.Value <--> std.json.JSONValue.

### CODE REVIEW

**Comment by repeatedly** [comment]
Tests failed. Is this from old dmd version?
Updating to dmd 2.067 resolves this problem?

**Comment by Groterik** [comment]
I have v2.067.0 and `MODEL=64 make -f posix.mak unittest` runs successfully without any message. But as I can see in your travis config, dmd v2.064.2 is installed and runs for testing. I will try to check and fix all the errors if it is necessary.

**Comment by repeatedly** [comment]
Could you update Travis-CI config for dmd 2.067?
After that, test will run automatically and we can judge old compiler is problem or not.

**Comment by Groterik** [comment]
It seems that tests have just been passed.

**Comment by repeatedly** [comment]
Sorry for the late. dmd 2.064 is older so we can ignore earlier versions.

**Pull request merged**
